[profile.default]
src = "contracts"
out = "out"
#libs = ["lib", ".deps/npm"]
#libs = ["lib"]

solc_version = '0.8.19'
auto_detect_solc = false
optimizer = true
optimizer_runs = 200

remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "erc721a=.deps/npm/erc721a/",
    "base64-sol=.deps/npm/base64-sol/",
    "operator-filter-registry/=lib/operator-filter-registry/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config